# Generated by Django 5.1.1 on 2024-09-23 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("your_help_coach", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cowrielogattack",
            name="description",
            field=models.TextField(null=True),
        ),
    ]
