# Generated by Django 5.1 on 2024-11-15 13:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("your_help_coach", "0002_cowrielogattack_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cowrielogattack",
            name="description",
            field=models.TextField(default="no description available"),
        ),
    ]
