# Generated by Django 5.1.1 on 2024-12-07 13:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("your_help_coach", "0003_alter_cowrielogattack_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cowrielogattack",
            name="attack_name",
            field=models.CharField(max_length=255),
        ),
    ]
