# Generated by Django 5.1.1 on 2024-09-09 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AttackType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attack_type", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField()),
            ],
        ),
    ]
