# Generated by Django 5.1.1 on 2024-09-23 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ask_me", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tips",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
            ],
        ),
    ]
