# Generated by Django 5.1 on 2024-11-15 16:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ask_me", "0003_classificationhistory_qahistory_summaryhistory"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="classificationhistory",
            name="dataAttr",
        ),
        migrations.RemoveField(
            model_name="classificationhistory",
            name="duration",
        ),
        migrations.RemoveField(
            model_name="classificationhistory",
            name="eventid",
        ),
        migrations.RemoveField(
            model_name="classificationhistory",
            name="input",
        ),
        migrations.RemoveField(
            model_name="classificationhistory",
            name="kexAlgs",
        ),
        migrations.RemoveField(
            model_name="classificationhistory",
            name="keyAlgs",
        ),
        migrations.RemoveField(
            model_name="classificationhistory",
            name="message",
        ),
        migrations.RemoveField(
            model_name="classificationhistory",
            name="protocol",
        ),
        migrations.RemoveField(
            model_name="classificationhistory",
            name="username",
        ),
        migrations.AddField(
            model_name="classificationhistory",
            name="input_log",
            field=models.TextField(default="None"),
        ),
    ]
