# Generated by Django 5.1.1 on 2024-12-02 14:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ask_me", "0005_classificationhistory_actual_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="classificationhistory",
            name="probability",
            field=models.TextField(default="None"),
        ),
    ]
